# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f3aabeb21937f1c4351e6e351db0c89"
application_url = "https://ecommerce-app-examples-verce.vercel.app/"
embedded = true
name = "example-app"
handle = "example-app222"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_orders, write_orders"

[auth]
redirect_urls = [ "https://ecommerce-app-examples-verce.vercel.app/api/auth" ]

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "pruebas-aplicaciones-bm.myshopify.com"
automatically_update_urls_on_dev = false
